version: "3.4"

# this network is used by mongo and api services so that they can speak to each other
networks:
    net5tutorial:
     external: true

volumes:
  mongodbdata:

services:
 mongo:
   image: mongo
   restart: always
   ports:
    - 27017:27017
   environment:
    - MONGO_INITDB_ROOT_USERNAME=mongoadmin
    - MONGO_INITDB_ROOT_PASSWORD=password123
   volumes:
    - mongodbdata:/data/db
   networks: 
    - net5tutorial

 catalog:
    image: jclaridad07/catalog:v4.1.14    
    networks: 
    - net5tutorial
    ports:
      - 8080:80
      - 8081:443
    environment:
        - MongoDBSettings:Host=mongo
        - MongoDBSettings:Password=password123
        - ASPNETCORE_ENVIRONMENT=Development    