apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  labels:
    app: catalog
spec:
  selector:
    matchLabels:
      app: catalog
  strategy: {}
  template:
    metadata:
      labels:
        app: catalog        
    spec:
      containers:
        - name: catalog-container
          image: jclaridad07/catalog:v4.1.23
          ports:
            - containerPort: 80
            #- containerPort: 8080
            #- containerPort: 8081
            #- containerPort: 443
          resources: {}
          env:
            - name: MongoDBSettings__Host
              value: mongo
            - name: MongoDBSettings__Password
              value: password123  
              #valueFrom: 
                #secretKeyRef:
                    #name: catalog-secrets
                    #key: mongodb-password
          livenessProbe: 
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
                path: /health/live
                port: 80
          readinessProbe: 
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
                path: /health/ready
                port: 80
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
    name: catalog-service
spec:
  selector:    
    app.kubernetes.io/name: catalog
  #type: LoadBalancer
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 80
    #- name: "80"
      #port: 80
      #targetPort: 80
    #- name: "8080"
      #port: 8080
      #targetPort: 80
    #- name: "8081"
      #port: 8081
      #targetPort: 443
  




            
            
