apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
          - "mongod"
          - "--bind_ip"
          - "0.0.0.0"
          #resources: 
            #limits:
                #memory: "128Mi"
                #cpu: "500m"
          ports:
            - containerPort: 27017            
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "mongoadmin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password123
              #valueFrom: 
               #secretKeyRef:
                #name: catalog-secrets
                #key: mongodb-password
          volumeMounts:
            - mountPath: /data/db
              name: mongodbdata
  volumeClaimTemplates:
    - metadata:
        name: mongodbdata
      spec:
        accessModes:  
        - ReadWriteOnce
        resources: 
         requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
    name: mongo
    labels:
        name: mongo
spec:
  ports:
   - port: 27017
     targetPort: 27017
    #- name: "27017"
      #port: 27017
      #targetPort: 27017
  selector:
    app: mongo
  clusterIP: None  
    
    